#' Generate Monthly Drought Bulletin
#'
#' Automatically generates an HTML or PDF bulletin summarising the current
#' drought situation, including alerts, time series plots, and agricultural
#' recommendations.
#'
#' @param index_data Tibble. SPI or SPEI data from \code{\link{calc_spi}} or
#'   \code{\link{calc_spei}}.
#' @param drought_result List. Output of \code{\link{detect_drought}}.
#' @param alerts Tibble. Output of \code{\link{generate_alerts}}.
#' @param region Character. Region name. Default: \code{"Study area"}.
#' @param output_format Character. \code{"html"} or \code{"pdf"}.
#'   Default: \code{"html"}.
#' @param output_file Character. Path for the output file. Default: auto-generated
#'   in the current working directory.
#' @param author Character. Author name for the bulletin. Default: \code{"droughtwatch"}.
#'
#' @return Invisibly returns the path to the generated bulletin.
#'
#' @examples
#' \dontrun{
#' data(morocco_climate)
#' spi    <- calc_spi(morocco_climate, scales = 3)
#' dr     <- detect_drought(spi)
#' alerts <- generate_alerts(dr, region = "Beni Mellal-Khenifra")
#' generate_monthly_bulletin(spi, dr, alerts,
#'   region = "Beni Mellal-Khenifra",
#'   output_format = "html")
#' }
#'
#' @export
generate_monthly_bulletin <- function(index_data,
                                       drought_result,
                                       alerts,
                                       region       = "Study area",
                                       output_format = "html",
                                       output_file  = NULL,
                                       author       = "droughtwatch") {

  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' required. Install with: install.packages('rmarkdown')")
  }

  # Auto-generate output filename
  if (is.null(output_file)) {
    date_str    <- format(Sys.Date(), "%Y%m")
    ext         <- if (output_format == "pdf") "pdf" else "html"
    output_file <- file.path(getwd(),
                             paste0("drought_bulletin_", date_str, ".", ext))
  }

  # Prepare data for the template
  episodes      <- drought_result$episodes
  active_alerts <- alerts[alerts$alert_level != "NONE", ]
  index_col     <- grep("^(spi|spei)_", names(index_data), value = TRUE)[1]
  latest        <- index_data[!is.na(index_data[[index_col]]), ]
  latest        <- latest[nrow(latest), ]

  # Write inline Rmd template
  template_path <- file.path(tempdir(), "drought_bulletin_template.Rmd")

  rmd_content <- paste0(
'---
title: "Monthly Drought Bulletin"
subtitle: "Region: ', region, '"
author: "', author, '"
date: "`r format(Sys.Date(), \'%B %Y\')`"
output:
  ', if (output_format == "pdf") "pdf_document" else "html_document", ':
    toc: true
    toc_depth: 3
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(droughtwatch)
library(ggplot2)
```

# 1. Executive Summary

This bulletin summarises drought conditions for **', region, '** as of `r format(Sys.Date(), "%B %Y")`.

**Current Index Value:** `r round(latest[[index_col]], 2)` (`r latest[[paste0("class_", sub(".*_", "", index_col))]]`)

**Active Alerts:** `r nrow(active_alerts)`

**Total Episodes Detected:** `r nrow(episodes)`

---

# 2. Current Drought Status

```{r status-table}
knitr::kable(latest[, c("date", index_col)],
             caption = "Latest Index Values",
             digits  = 3)
```

---

# 3. Time Series

```{r timeseries, fig.height=4}
plot_drought_timeseries(index_data, index_col = index_col, interactive = FALSE)
```

---

# 4. Active Alerts

```{r alerts}
if (nrow(active_alerts) > 0) {
  knitr::kable(active_alerts[, c("date","alert_level","message")],
               caption = "Active Drought Alerts")
} else {
  cat("No active drought alerts at this time.")
}
```

---

# 5. Recent Episodes

```{r episodes}
if (nrow(episodes) > 0) {
  knitr::kable(episodes, caption = "Detected Drought Episodes", digits = 2)
} else {
  cat("No drought episodes detected in the record.")
}
```

---

# 6. Agricultural Recommendations

Based on current conditions:

- **Irrigation:** ', .get_irrigation_advice(latest[[index_col]]), '
- **Crop management:** ', .get_crop_advice(latest[[index_col]]), '
- **Risk monitoring:** Continue monthly SPI/SPEI tracking and NDVI monitoring.

---

*Generated by the **droughtwatch** R package — Sohaib Jabrane*
')

  writeLines(rmd_content, template_path)

  message("Rendering bulletin to: ", output_file)
  rmarkdown::render(
    input       = template_path,
    output_file = output_file,
    quiet       = TRUE,
    envir       = new.env(parent = globalenv())
  )

  message("Bulletin generated: ", output_file)
  invisible(output_file)
}

# Internal helpers for recommendations
.get_irrigation_advice <- function(spi_val) {
  if (is.na(spi_val))        return("Data unavailable.")
  if (spi_val <= -2.0)       return("Emergency irrigation required. Activate all water sources.")
  if (spi_val <= -1.5)       return("Increase irrigation frequency. Monitor soil moisture daily.")
  if (spi_val <= -1.0)       return("Supplement natural rainfall with irrigation.")
  return("Normal irrigation schedule recommended.")
}

.get_crop_advice <- function(spi_val) {
  if (is.na(spi_val))        return("Data unavailable.")
  if (spi_val <= -2.0)       return("Consider drought-tolerant varieties. Delay planting if possible.")
  if (spi_val <= -1.5)       return("Prioritise high-value crops. Mulch to reduce evaporation.")
  if (spi_val <= -1.0)       return("Monitor crop stress. Apply foliar nutrition if needed.")
  return("Normal agronomic practices apply.")
}
